version: 0.1.0.{build}
os: Visual Studio 2015
environment:
  NUGETKEY:
    secure: z2fJQckgBQJ7IKfjOyrZYPM2+xDj4xYuqaUDBG7MrJs+b1bNc0vzYMTxpF6Sb1mA
test: off
build_script:
- cmd: build.cmd ci nugetkey=%NUGETKEY% nugetpublishurl=https://www.myget.org/F/saladlab/api/v2/package nugetprerelease=%APPVEYOR_BUILD_NUMBER%
artifacts:
  - path: './bin/nuget/*.nupkg'
    name: NugetPackage
cache:
- packages -> **\packages.config
